VERSION="2.1.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.yushi.moe/stellar/federation"
ACCOUNTS=[]

[DOCUMENTATION]
ORG_URL="https://yushi.moe/"
ORG_DESCRIPTION="personal;"

[[PRINCIPALS]]
name="yushijinhun"
email="me@yushi.moe"
telegram="yushijinhun"
twitter="yushijinhun"
github="yushijinhun"

